version: "3.9"

volumes:
  caddy_data: {}
  db:
    driver: local
  cache:
    driver: local

networks:
  gateway-network:
    name: gateway-network
    internal: true
  services-network:
    name: services-network
    internal: true
  reverse-proxy:
    name: reverse-proxy

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=reverse-proxy
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  caddy-services:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=services-network
    networks:
      - services-network
      - gateway-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - services-network
    volumes:
      - db:/data/db

  redis:
    image: redis
    restart: always
    networks:
      - gateway-network
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  frontend:
    image: keypea/frontend
    depends_on:
      - caddy
    build:
      context: frontend
      dockerfile: ./Dockerfile
    networks:
      - reverse-proxy
    labels:
      caddy: frontend.localhost
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 5000}}"
    environment:
      VITE_GATEWAY_HOST: gateway.localhost

  gateway:
    image: keypea/gateway
    depends_on:
      - redis
      - caddy
    build:
      context: gateway
      dockerfile: ./Dockerfile
    networks:
      - reverse-proxy
      - gateway-network
      - services-network
    labels:
      caddy: gateway.localhost
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 5001}}"
    environment:
      HANAMI_ENV: production
      HMAC_SECRET: tpJuMpJfJVzFcVUNebwgTYwJQFVCxyhEBqUUfCUuVTdjkSUnUd
      AUTH_API_HOST: auth-service
      AUTH_API_PORT: 5002
      AUTH_API_SECRET: example
      SECRETS_API_HOST: secrets-service
      SECRETS_API_PORT: 5003
      SECRETS_API_SECRET: example
      REDIS_URL: redis://redis:6379/0

  auth-service:
    image: keypea/auth-service
    depends_on:
      - mongo
    build:
      context: auth-service
      dockerfile: ./Dockerfile
    networks:
      - services-network
    hostname: auth-service
    labels:
      caddy-services.tls: internal
      caddy-services.reverse_proxy: "{{upstreams 5002}}"
    environment:
      RACK_ENV: production
      MONGODB_HOST: mongo:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: secret
      MONGODB_DATABASE: auth-service-dev

  secrets-service:
    image: keypea/secrets-service
    depends_on:
      - mongo
    build:
      context: secrets-service
      dockerfile: ./Dockerfile
    networks:
      - services-network
    hostname: secrets-service
    labels:
      caddy-services.tls: internal
      caddy-services.reverse_proxy: "{{upstreams 5003}}"
    environment:
      RACK_ENV: production
      MONGODB_HOST: mongo:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: secret
      MONGODB_DATABASE: secrets-service-dev
