# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "apia", "~> 3.0"
gem "bcrypt"
gem "mongoid", "~> 8.0.2"
gem "puma"
gem "rack"
gem "rack-console"

group :development, :test do
  gem "pry-remote"
  gem "dotenv"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "rspec", require: false
end
