# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "apia", "~> 3.0"
gem "rack"
gem "rack_csrf"
gem "rack-cors"
gem "rspec", require: false

group :development do
  gem "pry-remote"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
end
